biker_01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # users app
    path('users/', include('users.urls', namespace='users')),
    # bikes app
    path('', include('bikes.urls', namespace='bikes')),
]

bikes/urls.py
from django.urls import path
from bikes.views import start, ClientsListView, BikesListView, \
    ServicesListView, ClientDetailView, BikeDetailView, ServiceDetailView, client_extra_view, \
    add_client, ClientUpdateView, BikeUpdateView, ServiceUpdateView, add_bike, add_service, bike_extra_view

app_name = 'bikes'

urlpatterns = [
    path('', start, name='start'),
    path('clients', ClientsListView.as_view(), name='clients'),
    # path('client/<str:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client/<str:pk>', client_extra_view, name='client_detail'),
    path('add_client/', add_client, name='add_client'),
    path('update_client/<str:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('bikes/', BikesListView.as_view(), name='bikes'),
    path('bike/<str:pk>', bike_extra_view, name='bike_detail'),
    path('update_bike/<str:pk>', BikeUpdateView.as_view(), name='update_bike'),
    path('add_bike/<str:pk>', add_bike, name='add_bike'),
    path('services', ServicesListView.as_view(), name='services'),
    path('service/<str:pk>', ServiceDetailView.as_view(), name='service_detail'),
    path('update_service/<str:pk>', ServiceUpdateView.as_view(), name='update_service'),
    path('add_service/<str:pk>', add_service, name='add_service'),
]

bikes/models.py
from uuid import uuid4
from django.db import models
from users.models import Business


class Client(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False, unique=True)
    name = models.CharField(max_length=250, unique=True)
    business = models.ForeignKey(Business, on_delete=models.CASCADE)
    email = models.EmailField(blank=True)
    phone = models.IntegerField(blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return f'{self.name} - {self.business}'


class Bike(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False, unique=True)
    owner = models.ForeignKey(Client, on_delete=models.CASCADE)
    mark = models.CharField(max_length=250)
    model = models.CharField(max_length=250, blank=True)
    year = models.IntegerField(blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return f'{self.mark}-{self.model} of {self.owner}'


class Service(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False, unique=True)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    bike = models.ForeignKey(Bike, on_delete=models.CASCADE)
    start = models.DateField(auto_now_add=True)
    end = models.DateField(blank=True)
    price = models.FloatField(blank=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return f'{self.client} - {self.start}'

bikes/forms.py
from django.forms import ModelForm
from bikes.models import Client, Bike, Service


class ClientForm(ModelForm):
    class Meta:
        model = Client
        fields = ['name', 'email', 'phone', 'description']


class BikeForm(ModelForm):
    class Meta:
        model = Bike
        fields = ['mark', 'model', 'year', 'description']


class ServiceForm(ModelForm):
    class Meta:
        model = Service
        fields = ['end', 'price', 'description']

bikes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView

from bikes.forms import ClientForm, BikeForm, ServiceForm
from bikes.models import Client, Bike, Service


def start(request):
    return render(request, 'start.html')


class ClientsListView(ListView):
    model = Client
    template_name = 'list_view.html'
    context_object_name = 'clients_list'

    def get_context_data(self, **kwargs):
        login_user = self.request.user
        business = login_user.employee_of.business
        business_clients = Client.objects.filter(business=business)
        return {'clients_list': business_clients}


class ClientDetailView(DetailView):
    model = Client
    template_name = 'client_detail.html'


def client_extra_view(request, pk):
    client = Client.objects.get(pk=pk)
    bikes = Bike.objects.filter(owner=client)
    services = Service.objects.filter(client=client)
    return render(request, 'client_detail.html', {'client': client, 'bikes': bikes, 'services': services})


def add_client(request):
    login_user = request.user
    business = login_user.employee_of.business
    if request.method == 'POST':
        form = ClientForm(request.POST)
        if form.is_valid():
            new_client = form.save(commit=False)
            new_client.business = business
            new_client.save()
            return redirect('bikes:client_detail', new_client.id)
    else:
        form = ClientForm()
    return render(request, 'form.html', {'form': form})


class ClientUpdateView(UpdateView):
    model = Client
    fields = ['name', 'email', 'phone', 'description']
    template_name = 'form.html'

    def get_success_url(self):
        return reverse_lazy('bikes:client_detail', args=[self.object.pk])


class BikesListView(ListView):
    model = Bike
    template_name = 'list_view.html'
    context_object_name = 'bikes_list'

    def get_context_data(self):
        login_user = self.request.user
        business = login_user.employee_of.business
        business_clients = Client.objects.filter(business=business)
        business_bikes = Bike.objects.filter(owner__business__client__in=business_clients).distinct()
        return {'bikes_list': business_bikes}


class BikeDetailView(DetailView):
    model = Bike
    template_name = 'bike_detail.html'


def bike_extra_view(request, pk):
    bike = get_object_or_404(Bike, pk=pk)
    services = Service.objects.filter(bike=bike)
    return render(request, 'bike_detail.html', {'bike': bike, 'services': services})


def add_bike(request, pk):
    login_user = request.user
    owner = get_object_or_404(Client, pk=pk)
    if request.method == 'POST':
        form = BikeForm(request.POST)
        if form.is_valid():
            new_bike = form.save(commit=False)
            new_bike.owner = owner
            new_bike.save()
            return redirect('bikes:bike_detail', new_bike.id)
    else:
        form = BikeForm()
    return render(request, 'form.html', {'form': form})


class BikeUpdateView(UpdateView):
    model = Bike
    fields = ['mark', 'model', 'year', 'description']
    template_name = 'form.html'

    def get_success_url(self):
        return reverse_lazy('bikes:bike_detail', args=[self.object.pk])


class ServicesListView(ListView):
    model = Service
    template_name = 'list_view.html'
    context_object_name = 'services_list'

    def get_context_data(self, **kwargs):
        login_user = self.request.user
        business = login_user.employee_of.business
        business_clients = Client.objects.filter(business=business)
        services_list = Service.objects.filter(client__business__client__in=business_clients).distinct()
        return {'services_list': services_list}


class ServiceDetailView(DetailView):
    model = Service
    template_name = 'service_detail.html'


class ServiceUpdateView(UpdateView):
    model = Service
    fields = ['end', 'price', 'description']
    template_name = 'form.html'

    def get_success_url(self):
        return reverse_lazy('bikes:service_detail', args=[self.object.pk])


def add_service(request, pk):
    bike = get_object_or_404(Bike, pk=pk)
    owner = Client.objects.get(pk=bike.owner.id)
    if request.method == 'POST':
        form = ServiceForm(request.POST)
        if form.is_valid():
            new_service = form.save(commit=False)
            new_service.client = owner
            new_service.bike = bike
            new_service.save()
            return redirect('bikes:service_detail', new_service.id)
    else:
        form = ServiceForm()
    return render(request, 'form.html', {'form': form})

bikes/templates/bike_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="card m-1 shadow">
            <div class="card-header">
                {{ bike.mark }}
                <a href="{% url 'bikes:update_bike' bike.id %}">
                    <button class="btn btn-info">edit</button>
                </a>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">model: {{ bike.model }}</li>
                <li class="list-group-item">year: {{ bike.year }}</li>
                <li class="list-group-item">owner:
                    <a href="{% url 'bikes:client_detail' bike.owner.id %}">{{ bike.owner }}</a>
                </li>
                <li class="list-group-item">description: <p>
                    {{ bike.description }}
                </p></li>
            </ul>
        </div>
        <div class="row">
            <p>services:</p>
            <a href="{% url 'bikes:add_service' bike.id %}">
                <button class="btn btn-success">
                    add service
                </button>
            </a>
            {% for service in services %}
                <div class="col col-3">
                    <div class="card m-1 shadow">
                        <div class="card-header">
                            <a href="{% url 'bikes:service_detail' service.id %}">{{ service.bike }}</a>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ service.start }}-{{ service.end }}</li>
                            <li class="list-group-item">{{ service.price }}</li>
                        </ul>
                    </div>
                </div>
            {% empty %}
            {% endfor %}

        </div>

    </div>
{% endblock %}

bikes/templates/client_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="card m-1 shadow">
            <div class="card-header">
                {{ client.name }}
                <a href="{% url 'bikes:update_client' client.id %}">
                    <button class="btn btn-info">edit</button>
                </a>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">email: {{ client.email }}</li>
                <li class="list-group-item">phone: {{ client.phone }}</li>
                <li class="list-group-item">description: <p>
                    {{ client.description }}
                </p></li>
            </ul>
        </div>
        <div class="row">
            <p>bikes:</p>
            <a href="{% url 'bikes:add_bike' client.id %}">
                <button class="btn btn-warning">
                    add bike
                </button>
            </a>
            {% for bike in bikes %}
                <div class="col col-3">
                    <div class="card m-1 shadow">
                        <div class="card-header">
                            <a href="{% url 'bikes:bike_detail' bike.id %}">{{ bike.mark }}</a>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ bike.model }}</li>
                            <li class="list-group-item">{{ bike.year }}</li>
                        </ul>
                    </div>
                </div>
            {% empty %}
            {% endfor %}
        </div>
        <div class="row">
            <p>services:</p>
            {% for service in services %}
                <div class="col col-3">
                    <div class="card m-1 shadow">
                        <div class="card-header">
                            <a href="{% url 'bikes:service_detail' service.id %}">{{ service.bike }}</a>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">{{ service.start }}-{{ service.end }}</li>
                            <li class="list-group-item">{{ service.price }}</li>
                        </ul>
                    </div>
                </div>
            {% empty %}
            {% endfor %}

        </div>

    </div>
{% endblock %}

bikes/templates/form.html
{% extends "base.html" %}

{% block content %}
    <div class="m-2">
        <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="fieldWrapper m-1">
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field}}
                    {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                    {% endif %}
                </div>
            {% endfor %}
            <input type="submit" value="SAVE" class="btn btn-primary">
        </form>
    </div>
{% endblock %}

bikes/templates/list_view.html
{% extends "base.html" %}

{% block content %}

    {% if clients_list %}
        <h2>Clients List</h2>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">name</th>
                <th scope="col">email</th>
                <th scope="col">phone</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for client in clients_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <th><a href={% url 'bikes:client_detail' client.id %}>
                        <button class="btn btn-info">{{ client.name }}</button>
                    </a></th>
                    <th>{{ client.email }}</th>
                    <th>{{ client.phone }}</th>
                    <th>
                        <a href="{% url 'bikes:update_client' client.id %}">
                            <button class="btn btn-primary">edit</button>
                        </a>
                    </th>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% elif bikes_list %}
        <h2>Bikes List</h2>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">owner</th>
                <th scope="col">mark</th>
                <th scope="col">model</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for bike in bikes_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <th>{{ bike.owner }}</th>
                    <th><a href={% url 'bikes:bike_detail' bike.id %}>
                        <button class="btn btn-info">{{ bike.mark }}</button>
                    </a></th>
                    <th>{{ bike.model }}</th>
                    <th>
                        <a href="{% url 'bikes:update_bike' bike.id %}">
                            <button class="btn btn-info">edit</button>
                        </a>
                    </th>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% elif services_list %}
        <h2>Services List</h2>
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">client</th>
                <th scope="col">bike</th>
                <th scope="col">start</th>
                <th scope="col">end</th>
                <th scope="col">price</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for service in services_list %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <th><a href={% url 'bikes:service_detail' service.id %}>
                        <button class="btn btn-info">{{ service.client }}</button>
                    </a></th>
                    <th>{{ service.bike }}</th>
                    <th>{{ service.start }}</th>
                    <th>{{ service.end }}</th>
                    <th>{{ service.price }}</th>
                    <th>
                        <a href="{% url 'bikes:update_service' service.id %}">
                            <button class="btn btn-info">edit</button>
                        </a>
                    </th>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

bikes/templates/service_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="card m-1 shadow">
            <div class="card-header">
                <a href="{% url 'bikes:bike_detail' object.bike.id %}">{{ object.bike }}</a>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">client:
                    <a href="{% url 'bikes:client_detail' object.client.id %}">{{ object.client }}</a>
                </li>
                <li class="list-group-item">dates: {{ object.start }} - {{ object.end }}</li>
                <li class="list-group-item">price: {{ object.price }}</li>
                <li class="list-group-item">description: <p>
                    {{ object.description }}
                </p></li>
                <li class="list-group-item">
                    <a href="{% url 'bikes:update_service' object.id %}">
                        <button class="btn btn-info">edit</button>
                    </a>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}