biker_01/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # users app
    path('users/', include('users.urls', namespace='users')),
    # bikes app
    path('', include('bikes.urls', namespace='bikes')),
]

bikes/urls.py
from django.urls import path
from bikes.views import start, ClientsListView, BikesListView, \
    ServicesListView, ClientDetailView, BikeDetailView, ServiceDetailView, client_extra_view, \
    add_client, ClientUpdateView, BikeUpdateView, ServiceUpdateView, add_bike, add_service, bike_extra_view

app_name = 'bikes'

urlpatterns = [
    path('', start, name='start'),
    path('clients', ClientsListView.as_view(), name='clients'),
    # path('client/<str:pk>', ClientDetailView.as_view(), name='client_detail'),
    path('client/<str:pk>', client_extra_view, name='client_detail'),
    path('add_client/', add_client, name='add_client'),
    path('update_client/<str:pk>', ClientUpdateView.as_view(), name='update_client'),
    path('bikes/', BikesListView.as_view(), name='bikes'),
    path('bike/<str:pk>', bike_extra_view, name='bike_detail'),
    path('update_bike/<str:pk>', BikeUpdateView.as_view(), name='update_bike'),
    path('add_bike/<str:pk>', add_bike, name='add_bike'),
    path('services', ServicesListView.as_view(), name='services'),
    path('service/<str:pk>', ServiceDetailView.as_view(), name='service_detail'),
    path('update_service/<str:pk>', ServiceUpdateView.as_view(), name='update_service'),
    path('add_service/<str:pk>', add_service, name='add_service'),
]

users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        extra_context={'next': 'bikes:start'}
    ), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        next_page=reverse_lazy('users:login')
    ), name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>biker</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="h-100 bg-light">
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow">
        <div class="container-fluid">
            <a class="navbar-brand" href={% url 'bikes:start' %}>Biker</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            CLIENTS
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href={% url 'bikes:clients' %}>all clients</a></li>
                            <li><a class="dropdown-item" href={% url 'bikes:add_client' %}>add client</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            BIKES
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href={% url 'bikes:bikes' %}>all bikes</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            SERVICES
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href={% url 'bikes:services' %}>all services</a></li>
                        </ul>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                Login: {{ user.username }}
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href={% url 'users:logout' %}>Logout</a></li>
                            </ul>
                        <li class="nav-item">
                            <a class="nav-link">Business: {{ user.employee_of.business }}</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link active" href={% url 'users:login' %}>Login</a>
                        </li>
                    {% endif %}
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link active" href={% url 'admin:login' %}>Admin</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
    <div class="fixed-bottom">
        <p>
            copyright 2021 slawekj
        </p>
    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>